###Autogenerated code from internal Makefile
### Sourced from file: Apps/ui_nbs/FullStudyApp.ipynb

#| to_script
# Import the needed components
from ai_classroom_suite.UIBaseComponents import *
from ai_classroom_suite.UIBaseComponents import FullStudyApp

# Launch the relevant component
FullStudyApp.queue().launch(server_name='0.0.0.0', server_port=7860)
