# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/self_study_prompts.ipynb.

# %% auto 0
__all__ = ['MC_QUIZ_DEFAULT', 'SHORT_ANSWER_DEFAULT', 'FILL_BLANK_DEFAULT', 'SEQUENCING_DEFAULT', 'RELATIONSHIP_DEFAULT',
           'CONCEPTS_DEFAULT', 'REAL_WORLD_EXAMPLE_DEFAULT', 'RANDOMIZED_QUESTIONS_DEFAULT', 'SELF_STUDY_PROMPT_NAMES',
           'SELF_STUDY_DEFAULTS', 'list_all_self_study_prompt_keys', 'list_all_self_study_prompts',
           'list_default_self_prompt_varnames', 'print_all_self_study_prompts']

# %% ../nbs/self_study_prompts.ipynb 4
# used for pretty display
import pandas as pd

# %% ../nbs/self_study_prompts.ipynb 5
MC_QUIZ_DEFAULT = "Please design a 5 question multiple choice quiz about the provided text."

SHORT_ANSWER_DEFAULT = ("Please design a 5 question short answer quiz about the provided text. "
                        "The question types should be short answer. Expect the correct answers to be a few sentences long.")

FILL_BLANK_DEFAULT = """Create a 5 question fill in the blank quiz referencing parts of the provided text.
The "blank" part of the question should appear as "________". The answers should reflect what word(s) should go in the blank an accurate statement.
An example is as follows: "The author of the book is ______." The question should be a statement.
"""

SEQUENCING_DEFAULT = """Create a 5 question questionnaire that will ask me to recall the steps or sequence of events
in the provided text."""

RELATIONSHIP_DEFAULT = ("Create a 5 question quiz for the student that asks the student to identify relationships between"
                        "topics or concepts that are important to understanding this text.")

CONCEPTS_DEFAULT = """ Design a 5 question quiz that asks me about definitions or concepts of importance in the provided text."""

REAL_WORLD_EXAMPLE_DEFAULT = """Demonstrate how the provided context can be applied to solve a real world problem.
Ask me questions about how the demonstration you provided relates to solving a real world problem."""

RANDOMIZED_QUESTIONS_DEFAULT = """Generate a high-quality assessment consisting of 5 varied questions,
each of different types (open-ended, multiple choice, short answer, analogies, etc.)"""

SELF_STUDY_PROMPT_NAMES = ['MC_QUIZ_DEFAULT',
'SHORT_ANSWER_DEFAULT',
'FILL_BLANK_DEFAULT',
'SEQUENCING_DEFAULT',
'RELATIONSHIP_DEFAULT',
'CONCEPTS_DEFAULT',
'REAL_WORLD_EXAMPLE_DEFAULT',
'RANDOMIZED_QUESTIONS_DEFAULT']

# %% ../nbs/self_study_prompts.ipynb 7
# Define self study dictionary for lookup
SELF_STUDY_DEFAULTS = {'mc': MC_QUIZ_DEFAULT,
'short_answer': SHORT_ANSWER_DEFAULT,
'fill_blank': FILL_BLANK_DEFAULT,
'sequencing': SEQUENCING_DEFAULT,
'relationships': RELATIONSHIP_DEFAULT,
'concepts': CONCEPTS_DEFAULT,
'real_world_example': REAL_WORLD_EXAMPLE_DEFAULT,
'randomized_questions': RANDOMIZED_QUESTIONS_DEFAULT
} 

# Return list of all self study prompts
def list_all_self_study_prompt_keys():
    return list(SELF_STUDY_DEFAULTS.keys())

def list_all_self_study_prompts():
    return list(SELF_STUDY_DEFAULTS.values())
    
# Return list of all self study variable names
def list_default_self_prompt_varnames():
    return SELF_STUDY_PROMPT_NAMES

# Print as a table
def print_all_self_study_prompts():
    with pd.option_context('max_colwidth', None):
        display(pd.DataFrame({'SELF_STUDY_DEFAULTS key': list(SELF_STUDY_DEFAULTS.keys()),
        'Prompt': list(SELF_STUDY_DEFAULTS.values())}))

